# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7vx690tffg1157-2
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/grads/qxn5005/Documents/psu_VLSI/hw/hw3/hw3/vivado_Project/hw3.cache/wt [current_project]
set_property parent.project_path /home/grads/qxn5005/Documents/psu_VLSI/hw/hw3/hw3/vivado_Project/hw3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/grads/qxn5005/Documents/psu_VLSI/hw/hw3/hw3/code/mmcm/mmcm_i125_o100_o200_o400_o600/mmcm_i125_o100_o200_o400_o600_clk_wiz.v
  /home/grads/qxn5005/Documents/psu_VLSI/hw/hw3/hw3/code/FPGA/hdl/verilog/Quang_TRAFFIC_LIGHT.v
  /home/grads/qxn5005/Documents/psu_VLSI/hw/hw3/hw3/code/FPGA/hdl/verilog/fpga.v
}
read_xdc /home/grads/qxn5005/Documents/psu_VLSI/hw/hw3/hw3/code/FPGA/hdl/ucf/fpga.xdc
set_property used_in_implementation false [get_files /home/grads/qxn5005/Documents/psu_VLSI/hw/hw3/hw3/code/FPGA/hdl/ucf/fpga.xdc]

catch { write_hwdef -file fpga.hwdef }
synth_design -top fpga -part xc7vx690tffg1157-2
write_checkpoint -noxdef fpga.dcp
catch { report_utilization -file fpga_utilization_synth.rpt -pb fpga_utilization_synth.pb }
